### PR TITLE
Add option to save the rendered html

### PR DESCRIPTION
**Pull request by terrytangyuan**
The motivation for this is that I was always getting blank page after the browser pops up so at least I could save this file so that I am able to view it. 

I didn't roxygen the new parameter doc successfully due to the following error:
```
Error in get("text") : 
  Config file config.yml not found in current working directory or parent directories
```
This happens in master branch as well.

### CODE REVIEW

**Comment by jjallaire** [comment]
I do agree that it would be nice to have a function that saves rather than views html although I'd do this a bit differently. If this is just for debugging then I just checked in an alternative approach which simply returns the path to the run HTML file invisibly from the `view_run` function. Would this do what you need?

**Comment by terrytangyuan** [comment]
Yes that should work!

**Comment by jjallaire** [comment]
I also just added a `save_run_report` function which will save a copy what is displayed by `view_run`.

**Comment by terrytangyuan** [comment]
Sweet! I'll check it out soon!

**Pull request closed without merging**
